name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name, like 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runners work on all platforms

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (use LTS version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Change this if you need a different version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project, allowing warnings
      - name: Build project
        run: CI='' npm run build  # Setting CI='' disables "treat warnings as errors" behavior

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Adjust this to the correct build directory if needed
 
